name: EventoDemo 1
on: 
  pull_request:
    types: 
      - opened
      - edited
      - closed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Saida dos dados de eventos
          run: echo "${{ toJSON(github.event.action) }}"