name: Evento issues Teste 
on: 
  issues:
    types: [opened, edited, milestoned]
jobs:
  issuesTest:
    runs-on: ubuntu-latest
    steps:
      - name: Get Event
        run: | 
          echo "${{ toJSON(github.event.action) }}"
          echo "${{ toJSON(github.event.label) }}"
          echo "${{ toJSON(github.event.changes) }}"
          echo "${{ toJSON(github.event.milestone) }}"
          echo "${{ toJSON(github.event.sender) }}"
          echo "-----------------------------------------------"
          echo "${{ toJSON(github.event.issue) }}"
          echo "${{ toJSON(github.event) }}"
        